- name: Update Root user's Password
  become: yes
  user:
    name: root
    update_password: always
    password: "{{ 'password' | password_hash('sha512') }}"
  tags:
    - root
    - users

- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel
  tags:
    - users

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"
  tags:
    - users
