---
- name: Install apps
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
    aur_only: no
    update_cache: yes
    state: present
  with_items: "{{ apps }}"
  become: yes
  become_user: root
  tags:
    - apps

- name: Install node.js apps
  community.general.npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items: "{{ js_apps }}"
  become: yes
  tags:
    - js_apps
    - apps
