---
- name: Copy home dotfiles
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/
    force: True
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items: "{{ home_dotfiles }}"
  become: yes
  tags:
    - zsh
    - dotfiles
    - dotfiles-home

- name: Setup crontab job
  ansible.builtin.cron:
    name: "start up scripts"
    special_time: reboot
    job: /home/{{ username }}/.startup.sh
  tags:
    - startup
    - crontab
    - dotfiles
    - dotfiles-home

- name: Copy kitty dotfiles
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.config/kitty/
    force: True
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items:
    - "kitty/kitty.conf"
    - "kitty/current-theme.conf"
  become: yes
  tags:
    - kitty
    - dotfiles
    - dotfiles-kitty

- name: Copy KDE dotfiles
  copy:
    src: kde
    dest: /home/{{ username }}/.config/
    force: True
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rwx
  become: yes
  tags:
    - kde
    - dotfiles
    - dotfiles-kde

- name: Copy joplin dotfiles
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.config/joplin/
    force: True
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items:
    - "joplin/keymap.json"
  become: yes
  tags:
    - joplin
    - dotfiles
    - dotfiles-joplin

- name: copy ranger dotfiles
  copy:
    src: ranger
    dest: /home/{{ username }}/.config/
    force: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rwx
  become: yes
  tags:
    - ranger
    - dotfiles
    - dotfiles-ranger

- name: copy lf dotfiles
  copy:
    src: lf 
    dest: /home/{{ username }}/.config/
    force: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rwx
  become: yes
  tags:
    - lf
    - dotfiles
    - dotfiles-lf

- name: copy lf execute script
  copy:
    src: lf/lfrun
    dest: /home/{{ username }}/.local/bin/
    force: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rwx
  become: yes
  tags:
    - lf
    - dotfiles
    - dotfiles-lf

- name: copy lunarvim dotfiles
  copy:
    src: lvim
    dest: /home/{{ username }}/.config/
    force: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "644"
  tags:
    - lvim
    - dotfiles
    - dotfiles-lvim

- name: copy flameshot dotfiles
  copy:
    src: flameshot
    dest: /home/{{ username }}/.config/
    force: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "644"
  tags:
    - flameshot
    - dotfiles
    - dotfiles-flameshot

- name: copy espanso dotfiles
  copy:
    src: espanso
    dest: /home/{{ username }}/.config/
    force: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "644"
  tags:
    - espanso
    - dotfiles
    - dotfiles-espanso

- name: espanso service restart
  ansible.builtin.shell: |
    espanso service register
    espanso restart || /bin/true
  register: command_result
  failed_when: command_result.rc != 0
  changed_when:
    - "'successfully' in command_result.stdout"
    - "'espanso is already running!' in command_result.stderr_lines"
  tags:
    - espanso
    - dotfiles
    - dotfiles-espanso
