---
- name: Copy home dotfiles
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/
    force: True
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items: "{{ home_dotfiles }}"
  become: yes
  tags:
    - zsh
    - dotfiles
    - dotfiles-zsh

- name: Copy kitty dotfiles
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.config/kitty/
    force: True
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items:
    - "kitty/kitty.conf"
    - "kitty/current-theme.conf"
  become: yes
  tags:
    - kitty
    - dotfiles
    - dotfiles-kitty

- name: Copy KDE dotfiles
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.config/KDE
    force: True
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rwx
  with_items:
    - "kde/kde-shortcut-code.sh"
    - "kde/kde-shortcut-kitty.sh"
  become: yes
  tags:
    - kde
    - dotfiles
    - dotfiles-kde

- name: Copy joplin dotfiles
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.config/joplins/
    force: True
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items:
    - "joplin/keymap.json"
  become: yes
  tags:
    - joplin
    - dotfiles
    - dotfiles-joplin

- name: Copy ranger dotfiles
  copy:
    src: ranger
    dest: /home/{{ username }}/.config/
    force: True
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rwx
    become: yes
  tags:
    - ranger
    - dotfiles
    - dotfiles-ranger
