---
- name: Update cache and upgrade
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  register: pacmanout
  become: yes
  tags:
    - pre

- debug: msg="{{ pacmanout.stdout_lines }}"
  when: pacmanout.stdout_lines is defined

- name: Install base utils
  community.general.pacman:
    name: "{{ base_utils }}"
    state: present
  become: yes
  tags:
    - base
    - utils

- name: Upgrade the system using yay
  kewlfft.aur.aur:
    upgrade: yes
    use: yay
    aur_only: no
  become: yes
  tags:
    - base
    - utils

- name: Install utils
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
    aur_only: no
    state: present
  become: yes
  become_user: aur_builder
  with_items: "{{ utils }}"
  tags:
    - base
    - utils

- import_tasks: zsh.yml
- import_tasks: dotfiles.yml
