---
- name: Install ranger-plugins
  git:
    repo: "{{ item }}"
    dest: /home/{{ username }}/.config/ranger/plugins/{{ item.rsplit('/', 1)[-1] }}
    depth: 1
  with_items: "{{ ranger_plugins }}"
  become: yes
  tags:
    - ranger
    - ranger-plugin
